package org.culturegraph.mf.sql.util;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import org.culturegraph.mf.framework.MetafactureException;
import org.culturegraph.mf.framework.StreamReceiver;

public final class DirectQuery extends QueryBase {

	private final Statement statement;

	public DirectQuery(final Connection connection,
			final boolean emitGeneratedKeys) {
		this(connection, QueryBase.DEFAULT_ID_COLUMN, emitGeneratedKeys);
	}

	public DirectQuery(final Connection connection, final String idColumnLabel,
			final boolean emitGeneratedKeys) {
		super(connection, idColumnLabel, emitGeneratedKeys);
		try {
			statement = connection.createStatement();
		} catch (final SQLException e) {
			throw new MetafactureException(e);
		}
	}

	public void execute(final String sql) {
		try {
			statement.execute(sql, Statement.NO_GENERATED_KEYS);
		} catch (final SQLException e) {
			throw new MetafactureException(e);
		}
	}

	public void execute(final String sql, final StreamReceiver receiver) {
		try {
			statement.execute(sql, getAutoGeneratedKeysSetting());
		} catch (final SQLException e) {
			throw new MetafactureException(e);
		}
		processResults(statement, receiver);
	}

	public void close() {
		close(statement);
	}

}
